name: Daily - Goiko Menu

on:
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Create env file
      run: |
        touch .env
        echo TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} >> .env
        echo TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }} >> .env
        echo TELEGRAM_SEND_MESSAGE=${{ secrets.TELEGRAM_SEND_MESSAGE }} >> .env

        echo TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }} >> .env
        echo TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }} >> .env
        echo TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }} >> .env
        echo TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} >> .env
        echo TWITTER_SEND_TWEET=${{ secrets.TWITTER_SEND_TWEET }} >> .env

    - name: Execute cron
      run: npm run daily
